/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 * 
 * File: macros.c  
 * Author: konstantinos gkotzamanidis
 * Comments:
 * Revision history: 
 */
#include "../Libraries/macros.h"

/*
 *void reset_register(void)
 * Reset all the Register of Pic16F887. 
 */
void reset_register(void){
    PORTA = 0x00;
    PORTB = 0x00;
    PORTC = 0x00;
    PORTD = 0x00;
    PORTE = 0x0;
    INTCON = 0x00;
    PIR1 = 0x00;
    PIR2 = 0x00;
    T1CON = 0x00;
    T2CON = 0x00;
    SSPCON = 0x00;
    CCP1CON = 0x00;
    RCSTA = 0x00;
    CCP2CON =0x00;
    ADCON0 = 0x00;
    OPTION_REG = 0x00;
    TRISA = 0x00;
    TRISB = 0x00;
    TRISC = 0x00;
    TRISD = 0x00;
    TRISE = 0x0;
    PIE1 = 0x00;
    PIE2 = 0x00;
    PCON = 0x00;
    OSCCON = 0x00;
    OSCTUNE = 0x00;
    SSPCON2 = 0x00;
    SSPMSK = 0x00;
    SSPSTAT = 0x00;
    WPUB = 0x00;
    IOCB = 0x00;
    VRCON = 0x00;
    TXSTA = 0x00;
    SPBRG = 0x00;
    SPBRGH = 0x00;
    PWM1CON = 0x00;
    ECCPAS = 0x00;
    PSTRCON = 0x00;
    ADCON1 = 0x00;
    WDTCON = 0x00;
    CM1CON0 = 0x00;
    CM2CON0 = 0x00;
    CM2CON1 = 0x00;
    EEDAT = 0x00;
    EEADR = 0x00;
    EEDATH = 0x00;
    EEADRH = 0x00;
}

/*
 * void sleep(void)
 */
void sleep(void){
    __asm("SLEEP");
}