/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 *
 * File: onewire.h   
 * Author: konstantinos gkotzamanidis 
 * Comments:
 * Revision history: 
 */
#ifndef _ONEWIRE_H
#define _ONEWIRE_H

#include <stdio.h>
#include "delay.h"
#include "io.h"
#include "macros.h"

#define SEARCH_ROM 0xF0
#define READ_ROM 0x33
#define MATCH_ROM 0x55
#define SKIP_ROM 0xCC
#define SEARCH_ALARM 0xEC

#define CONVERT_T 0x44
#define WRITE_SCARTCHPAD 0x4E
#define READ_SCARTCHPAD 0xBE
#define COPY_SCARTCHPAD 0x48
#define RECALL_E 0xB8
#define READPOWERSUPLY 0xB4

uint8_t Sensor_Resolution_CMD;
double Sensor_Resolution_Time;
char Sensor_Data[64];
int Sensor_Pin;

void DS_Resolution(int resolution);
unsigned char DS_Reset(IO_PORT Sensor_Pin);
unsigned char DS_Read(IO_PORT Sensor_Pin);
unsigned char DS_Read_bit(IO_PORT Sensor_Pin);
void DS_Write(IO_PORT Sensor_Pin, uint8_t CMD);
void DS_Write_bit(IO_PORT Sensor_Pin, uint8_t CMD);
#endif