/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

#ifndef _PIC_IO_H
#define _PIC_IO_H

#include "Pic16f887_Utils.h"

typedef enum{
    RA_0,RA_1,RA_2,RA_3,RA_4,RA_5,RA_6,RA_7,
    RB_0,RB_1,RB_2,RB_3,RB_4,RB_5,RB_6,RB_7,
    RC_0,RC_1,RC_2,RC_3,RC_4,RC_5,RC_6,RC_7,
    RD_0,RD_1,RD_2,RD_3,RD_4,RD_5,RD_6,RD_7,
    RE_0,RE_1,RE_2,RE_3,RE_4,RE_5,RE_6,RE_7,
    R_NC = 0xff
}Pic_IO_Ports;

void Pic_IO_Mode(Pic_IO_Ports enum_pinNumber,uint8_t var_pinDir);
void Pic_IO_Write(Pic_IO_Ports enum_pinNumber,uint8_t var_pinValue);
uint8_t Pic_IO_Read(Pic_IO_Ports enum_pinNumber);

#endif
